### ISSUE TITLE
profile pic issue

### ISSUE THREAD

**Issue by ThenuSand** [serandomps/serandives#3]
when the user is going to put a profile picture,the system is automatically cropping picture and putting to the profile in some times it cropping the part that user needs to display so I think that is a issue

**Comment by serandomps** [comment]
A profile picture will have the same width/height ratio. So, user will have to crop it before hand to match the needed

**Comment by ThenuSand** [comment]
> when the user is going to put a profile picture,the system is automatically cropping picture and putting to the profile in some times it cropping the part that user needs to display so I think that is a issue
